### ISSUE TITLE
Comments on recent changes to cmake files

### ISSUE THREAD

**Issue by hmaarrfk** [pthom/imgui_bundle#290]
Thanks for being very responsive to the conda package. It is always helpful to work with the upstream developers to ensure a good user experience ^_^

I have a few comments on the recent changes. I looked through the recent history to find things that looked intersting my reading the commit message

1. Please don't use `FORCE` for CMake configuration variables. Often for various cross compilation situations it is useful to have some control of how CMake detects things. Variables are meant to be hints, with overrides in specific situations. 
https://github.com/pthom/imgui_bundle/commit/d0666babbb55aa66cf7e62f931538ca475971a4b
Please just let this be:
```
        # With conda, we can rely on finding python in the path
        set(Python_EXECUTABLE "python" CACHE STRING "" FORCE)
```
is not really necessary and honestly hurtful since I will be tempted to patch this away.

2. glfw library search path is not needed in conda. For conda installations, the Path is setup in such a way that 
```
def _glfw_set_search_path() -> None:
    return
```
is all one needs.

Furthermore, it is entirely conceivable that users have a system installation of:

* python from conda
* imgui_bundle installed through `pip`.

Its much more common of a usecase than you think. So by having the changes in 
https://github.com/pthom/imgui_bundle/commit/35c7e7d5f0b49bbdcc045e3009cec662775d79c7 
you are breaking that workflow.

3. pip based glfw package reliance is likely bad for your pip users.

Essentially, when you are building your own package, you are using the CMake mechanics to find the glfw library.
You then "load in" the glfw in python by "hijacking" the one from the pip installation. I'm not sure if you are involved with the package
https://github.com/FlorianRhiem/pyGLFW
but if you aren't this is a "big liability" since you aren't too sure what options were used at compile time, and if it is an ABI compatible library.
The "pip way" is to ship your own version of the glfw `.so` file, or to statically link. The "conda way" is to build a system to share the shared library. (hence why i love conda)

4. Just use `Python_SITELIB`: https://github.com/pthom/imgui_bundle/commit/d34be42ec25e3b00e8e1dcfae32a79c9b722a655 https://cmake.org/cmake/help/latest/module/FindPython.html

5. Thank you! https://github.com/pthom/imgui_bundle/commit/45173052465f0b3df85ca696a04fcadf84c6f258
6. Thank you! https://github.com/pthom/imgui_bundle/commit/5c1420f94f2fbefa7a6e7a0bc7f70ae7f8f24b72

Alright thats all i have for now! Thanks a bunch!!!!

**Comment by pthom** [comment]
Hello,

> 1. Please don't use FORCE for CMake configuration variables. Often for various cross compilation situations it is useful to have some control of how CMake detects things. Variables are meant to be hints, with overrides in specific situations.
https://github.com/pthom/imgui_bundle/commit/d0666babbb55aa66cf7e62f931538ca475971a4b

I reverted this commit: see 6e76fbdfea9dd5823ba69ce70bf2c7f54464238a

> 2. glfw library search path is not needed in conda.
Done, see 7e8651507f8390f350e690a2ecf570123e72fd95

> 4.  Just use Python_SITELIB: https://github.com/pthom/imgui_bundle/commit/d34be42ec25e3b00e8e1dcfae32a79c9b722a655 https://cmake.org/cmake/help/latest/module/FindPython.html

I reviewed the way this is handled in e610658fde8e0bf5825adbcdde789221e39a0cba.
These copies are only meant to be used when **not** building a wheel, but when debugging from within an IDE. They will not happen anymore in your case. By the way, I used Python_SITEARCH, because I deploy a platform dependent module.

**Comment by hmaarrfk** [comment]
Awesome.

**Comment by pthom** [comment]
> 3.  pip based glfw package reliance is likely bad for your pip users.
> Essentially, when you are building your own package, you are using the CMake mechanics to find the glfw library.
You then "load in" the glfw in python by "hijacking" the one from the pip installation. I'm not sure if you are involved with the package
https://github.com/FlorianRhiem/pyGLFW
but if you aren't this is a "big liability" since you aren't too sure what options were used at compile time, and if it is an ABI compatible library.
The "pip way" is to ship your own version of the glfw .so file, or to statically link. The "conda way" is to build a system to share the shared library. (hence why i love conda)

We are reaching a point that is crucial to the installation of imgui bundle when using pip (outside of conda): 
imgui_bundle relies on the usage of the glfw dynamic library it was compiled with.

Note: I am in no way related to pyGLFW. I am simply a user.

We have three cases:
* 1. Users who are running an application with hello-imgui or immapp, the C++ code will be responsible for calling glfw: everything happens smoothly (and there is no need to install pyGLFW in fact)
* 2. Users who run a "pure python backend": they will initialize glfw and opengl themselves, and do the drawing with python code (which will call OpenGL and glfw). No C++ code that call glfw should be involved (although it is linked).
* 3. Users who want to run a "mixed python backend": they will import glfw with python, initialize it, and rely on the C++ imgui_backends bindings to draw the imgui interface. In this case, it is crucial that imgui_bundle and glfw use the same dll. 

#### What pyGLFW installs
 pyGLFW deploys python code together with dynamic libraries (dll, dylib, so)
```bash
(v311) > pip install glfw

(v311) > ls v311/lib/python3.11/site-packages/glfw
GLFW.py         __init__.py     __pycache__     libglfw.3.dylib library.py   # contains the .dylib (for MacOS)
```

#### How pyGLFW search for a glfw dynamic library (system, or its own)

Inside pyGLFW, the code which searchs for the dll is here:

https://github.com/FlorianRhiem/pyGLFW/blob/7a683c3db9bb882c833d13233e22ec65b4edb3c7/glfw/library.py#L220-L255

This initialization will

1. **first test for a possible customization point (which I use in imgui_bundle)**

See https://github.com/FlorianRhiem/pyGLFW/blob/7a683c3db9bb882c833d13233e22ec65b4edb3c7/glfw/library.py#L220-L224 :
```python
if os.environ.get('PYGLFW_LIBRARY', ''):
    try:
        glfw = ctypes.CDLL(os.environ['PYGLFW_LIBRARY'])
    except OSError:
        glfw = None
```

2. **under windows favor a system wide installation**, and only use its own dll if no system wide install was found 
```python
elif sys.platform == 'win32':
    glfw = None  # Will become `not None` on success.

    # try Windows default search path
    try:
        glfw = ctypes.CDLL('glfw3.dll')
    except OSError:
        pass

    # try package directory
    if glfw is None:
        ...
```

3. **under linux and macOS, offer two flavors for the search**
 a frozen search, and a more generic version
See https://github.com/FlorianRhiem/pyGLFW/blob/7a683c3db9bb882c833d13233e22ec65b4edb3c7/glfw/library.py#L158-L204

(this code is convoluted, to be honest).

**Comment by hmaarrfk** [comment]
Hmm maybe I don't fully grasp things, but if users haven't complained then I guess it is good enough.....

**Comment by hmaarrfk** [comment]
Ps. this is still wrong:

https://github.com/pthom/imgui_bundle/commit/7e8651507f8390f350e690a2ecf570123e72fd95

Please don't do anything here and let me patch this out in the conda forge package.

a user may:
```
conda create --name py311_imgui_bundle python=3.11
conda activate py311_imgui_bundle
pip install imgui_bundle
# ^^^^^^^^^^^^^^^^^^^^ you now rely on pypi's glfw package, not conda-forge's
```
and they would not be able to find glfw because "is conda returns true" but what you really need is to find the package from pypi

**Comment by pthom** [comment]
> Please don't do anything here and let me patch this out in the conda forge package.

Done with https://github.com/pthom/imgui_bundle/commit/1c53eb22714922a96f7d2c2d7719f6c632fde034

However, some users will rely on having python bindings for gflw. Does the conda glfw package provide them?

**Comment by hmaarrfk** [comment]
General conda "wisdom" is:

1. Install all your conda dependencies.
2. Then install pip dependencies.

many people choose to have the only conda dependency be "python"
